### ISSUE TITLE
Test framework developing task

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/ocp-testing#27]
# 1 the scheduler 
1.1 parse the test case (check its validation first)
1.2 calling different services (test server, container pool)
in the first round (before 8.2), I'll use the demo test server and container pool
# 2 test server daemon
2.1 return the resource id to the scheduler (before 8.2)
# 3 container pool daemon
3.1 return the image availability and the id/name to the scheduler (before 8.2)

**Comment by zenlinTechnofreak** [comment]
@liangchenye I newed a issuse for your task for milestone 0.10 , u can update your job status or progress in this issuse, thus , I can get the progress.thx

**Comment by liangchenye** [comment]
Thanks! 
so far the progress of  the schedular and the test server daemon is 80%.
2 working days is enough, I'll submit that to test-engine directory in time.
