### ISSUE TITLE
Network testcase developing task

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/ocp-testing#28]
Network test:
finish network architechture coding, supportted docker only

**Comment by zenlinTechnofreak** [comment]
@ChengTiesheng  I newed a issuse of your task for milestone 0.10 , u can update your job status or progress in this issuse, thus , I can get the progress.thx

**Comment by ChengTiesheng** [comment]
Progress:
1.Finished some typical test cases;
2.Finished the test environment docker file;
3.Finished some container network deployment srcript.
However, certain work outputs have not been pushed to git hub, I will do this soon.

**Comment by ChengTiesheng** [comment]
Plan:
1.Enrich and modify the network test cases;
2.Finished the bash srcript of docker network deployment.
