### ISSUE TITLE
Hardware environment buiding task

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/ocp-testing#35]
@wangkirin  plz update your progress and the plan for hardware environment buiding task here.thanks.

**Comment by wangkirin** [comment]
I have finished the os installation  , and building the Openstack cluster .But now there is some problem with the SPES , i am working on it

**Comment by zenlinTechnofreak** [comment]
@wangkirin  what is the deadline for the issuses occured in hardware environment building job?

**Comment by wangkirin** [comment]
@zenlinTechnofreak next monday will be ok~~

**Comment by zenlinTechnofreak** [comment]
@wangkirin great, well done.
@maquanyi @mengfanliang @ChengTiesheng @liangchenye @haijunTan
