### ISSUE TITLE
About the satisfaction test of Open Container Specifications

### ISSUE THREAD

**Issue by wangkirin** [huawei-openlab/ocp-testing#45]
I have read the current document of  Open Container Specifications. In my point of view , we can test whether a container tech satisfied the  SPEC from the following items

### Runtime
- [ ] The container lifecycle have 3 status(process): create, start, stop
- [ ] Can be invoked several times
- [ ] Provide the function to stop the contairner from outside (host？)

### Configuration file
- [ ] The container’s top-level directory MUST contain a configuration file called `config.json`. 
         it seems that current RKT us `manifest.json` as a configuration file
- [ ]  Each container has exactly one root filesystem
- [ ]  The `path` under the root configuration ,MUST exist at the  **relative path**  declared by the field.
- [ ]  Supprot all linux filesystem listed in `/proc/filesystems`  by the kernel and ntfs filesystem of windows

**Comment by zenlinTechnofreak** [comment]
@wangkirin I just disscussed about the json file to use the go code and the cadvisor,  we can disscussed it later in the afternoon at the hotel.
