### ISSUE TITLE
Shall we need a open mail list group for the project?

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/ocp-testing#5]
Hi @maquanyi @mengfanliang 
    Shall we need a open mail list group for the project? it should be open and provide by third part, what about using google mail list Temporarily?

**Comment by mengfanliang** [comment]
gmail need vpn ,  outlook.com is right?

**Comment by zenlinTechnofreak** [comment]
@mengfanliang Can we request a  mail list group  from the outlook mail for free?
If it does, outlook is welcomed ofcause, can u two decided it and then tell me?thx.

**Comment by ChengTiesheng** [comment]
Hi, dear all, what about qq maillist? An example is given as below:
http://jingyan.baidu.com/article/4e5b3e195dd18b91901e2437.html

**Comment by ChengTiesheng** [comment]
Another choice, we can use 163 mail:
http://www.360doc.com/content/12/0220/17/55892_188111774.shtml

**Comment by zenlinTechnofreak** [comment]
It should be decided by @mengfanliang @maquanyi

**Comment by maquanyi** [comment]
We will build a IRC channal and Google Group for communication with developers.
