### ISSUE TITLE
how to intergrate the cadvisor to our porject, in the case of having source code changing and adaptor.

### ISSUE THREAD

**Issue by zenlinTechnofreak** [huawei-openlab/ocp-testing#7]
@maquanyi @mengfanliang 
As we disscussed last time, we should use cadvisor directly to do monitoring for containers,
And now, we have split the monitoring task into two parts,
1. enable support for ocp-testing project,
2. do develop on supporting the RKT container to the cadvisor.
To the first task,
    we have a question about how to intergrate into the ocp-testing, the situation is,
we should do some source code developing and adaptor  in the cadvisor source code, thus, to enable the cadvisor for ocp-testing.

so , my question is , in this case, how can we intergrate cadvisor to our project?

my opinion is:
      we can fork a repo from the cadvisor, and do the source changing in our forked repo, and then just use the forked repo in our project, and by the way, we do the pull&request to the main line of cadvisor.

so ,what about your opinion?

**Comment by zenlinTechnofreak** [comment]
@liangchenye @mengfanliang 
we found that there are two ways to intergrate cadvisor to our project.
A. use cadvisor/client, 
for example, 
import "github.com/google/cadvisor/client"

client, err = client.NewClient("http://localhost:8080/")
mInfo, err := client.MachineInfo()

but It is only can be used to send the result to the specied URL endpoint, but not to the local machine.

B. use API to install a net handle, the problem is the same as A, only support net url.

C. develop a storage in the cadvisor/storage,  we have to do more driver develop, in this way, we can support to storage data in native machine.

So, how to intergrate it should be determined by what we want!
Do we want to export data directly to the url endpoint throught the net, or to export data to the local machine?

It is emergence, we have to decided now.thx.

**Comment by liangchenye** [comment]
Hi Zhinan, cadivisor is one of the container performance monitoring tools. 
I thinking the integration here means: use this tool in the testcase, either by wrapping it in the script or using it directly.

**Comment by zenlinTechnofreak** [comment]
@liangchenye  we @liugenping decided that to write a client to support it.
according to the ouput fomat, we can keep changing in future.
thx.

**Comment by liangchenye** [comment]
I just confirmed with @liugenping, it is OK to integrate cadivisor to the framework without any change.
1) in the deploy part, run the cadivisor daemon in the related hostOS
2) at the end of the 'run' part, run your client to collect the output and redirect to a certain file.

**Comment by zenlinTechnofreak** [comment]
@liangchenye  yse, we @liugenping have determined it yestody.thx
